# configuracion servidor
server.port=12345

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/pericos_market
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# para que cree las tablas solo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
